set background=dark
set hlsearch
set incsearch
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent
set textwidth=0
set nowrap
set number
set scrolljump=5
set scrolloff=3
set backspace=start,eol
set ignorecase
set showmode
set ruler
set showmatch
set formatoptions=tcqor
set whichwrap=b,s,<,>,[,]
syntax on
