[tools]
bun = "latest"
deno = "latest"
go = "latest"
java = "latest"
julia = "latest"
node = "latest"
python = "latest"
rust = "1.95"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
fetch_remote_versions_timeout = "60s"

[settings.ruby]
ruby_build_opts = "CC=gcc CXX=g++"
