[tools]
bun = "1.2"
deno = "2.3"
dotnet = "9.0"
flyway = "11.8"
go = "1.24"
golangci-lint = "2.1"
gradle = "8.12"
java = "zulu-21"
julia = "1.11"
kotlin = "2.1"
maven = "3.9"
node = "23.11"
python = "3"
quarkus = "3.22"
ruby = "3.4"
rust = "1.86"
spring-boot = "3.4"
zig = "0.14"
php = "8.4"
ruff = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
