#!/usr/bin/env bash

pushd ~/personal/dotfiles/config-files/nvim
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/personal/dotfiles
git add .
git commit -m 'automated dev commit'
git push
popd

