#!/usr/bin/env bash
#
# Screenshot and Screen Recording Script for Wayland
# 
# Description: Rofi-based menu for taking screenshots and recording screen.
#              Supports selection, full screen, and specific outputs.
# 
# Usage: screenshot-record
# 
# Requirements: wf-recorder, grim, slurp, rofi, wl-copy (wl-clipboard)
# 
# Keybindings: Run via keybinding or rofi menu
# 
# Note: Screenshots saved to ~/pictures/screenshots/
#       Recordings saved to ~/videos/recordings/
#

wf-recorder_check() {
	if pgrep -x "wf-recorder" > /dev/null; then
		pkill -INT -x wf-recorder
		notify-send "Stopping all instances of wf-recorder" "$(cat /tmp/recording.txt)"
		wl-copy <"$(cat /tmp/recording.txt)"
		exit 0
	fi
}

wf-recorder_check

SELECTION=$(echo -e "screenshot selection\nscreenshot eDP-1\nscreenshot DP-1\nscreenshot both screens\nrecord selection\nrecord eDP-1\nrecord DP-1" | rofi -dmenu -p "󰄀 " -width 25 -lines 6)

IMG="${HOME}/pictures/screenshots/$(date +%Y-%m-%d_%H-%m-%s).png"
VID="${HOME}/videos/recordings/$(date +%Y-%m-%d_%H-%m-%s).mp4"

case "$SELECTION" in
"screenshot selection")
	grim -g "$(slurp)" "$IMG"
	wl-copy <"$IMG"
	notify-send "Screenshot Taken" "${IMG}"
	;;
"screenshot eDP-1")
	grim -c -o DP-1 "$IMG"
	wl-copy <"$IMG"
	notify-send "Screenshot Taken" "${IMG}"
	;;
"screenshot DP-1")
	grim -c -o DP-2 "$IMG"
	wl-copy <"$IMG"
	notify-send "Screenshot Taken" "${IMG}"
	;;
"screenshot both screens")
	grim -c -o eDP-1 "${IMG//.png/-eDP-1.png}"
	# grim -c -o DP-1 "${IMG//.png/-DP-2.png}"
	montage "${IMG//.png/-eDP-1.png}" "${IMG//.png/-DP-1.png}" -tile 2x1 -geometry +0+0 "$IMG"
	wl-copy <"$IMG"
	rm "${IMG//.png/-eDP-1.png}" "${IMG/.png/-DP-1.png}"
	notify-send "Screenshot Taken" "${IMG}"
	;;
"record selection")
	echo "$VID" >/tmp/recording.txt
	wf-recorder -a -g "$(slurp)" -f "$VID" &>/dev/null
	;;
"record eDP-1")
	echo "$VID" >/tmp/recording.txt
	wf-recorder -a -o DP-1 -f "$VID" &>/dev/null
	;;
"record DP-1")
	echo "$VID" >/tmp/recording.txt
	wf-recorder -a -o DP-2 -f "$VID" &>/dev/null
	;;
"record both screens")
	notify-send "recording both screens is not functional"
	;;
*) ;;
esac
