[tools]
bun = "latest"
deno = "latest"
dotnet = "latest"
go = "latest"
golangci-lint = "latest"
gradle = "latest"
java = "zulu-21"
julia = "latest"
kotlin = "latest"
maven = "latest"
node = "latest"
python = "3"
quarkus = "latest"
ruby = "latest"
rust = "latest"
spring-boot = "latest"
zig = "latest"
