# Desktop (donan) - Machine-specific configuration

# Monitor configuration
monitor=,preferred,auto,1.33,vrr,0

# Auto start
# exec-once = sleep 5 && uwsm-app -- $HOME/applications/pCloud.AppImage

# vi: ft=hypr
