# Laptop (nafain) - Machine-specific configuration

# Monitor configuration (variable refresh rate)
monitor=,preferred,auto,1.2,vrr,1

# Auto start
exec-once = sleep 5 && uwsm-app -- $HOME/Applications/pCloud.AppImage

# vi: ft=hypr
